[package]
name = "mysensors-logparser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#regex = "1.5.4"
log = "0.4"
nom = "7.0.0"
chrono = "0.4.19"
lazy_static = "1.4.0"
